function b64ToUtf8(b64) {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder('utf-8').decode(bytes);
}

const md = b64ToUtf8("U291cmNlOiByZXBvIGZpbGUgLmN1cnNvci9ydWxlcy9maWdtYS1kZXNpZ24tc3lzdGVtLm1kYyAoa2VlcCBpbiBzeW5jIHdpdGggR2l0KS4KCgojIEZpZ21hIOKGkiBDbG9ha2VkIOKAlCBEYXRhIFJlbW92YWwgKEZvciBEZXYpCgpDYW5vbmljYWwgZmlsZTogW0RhdGEgUmVtb3ZhbOKAlEZvciBEZXZdKGh0dHBzOi8vd3d3LmZpZ21hLmNvbS9kZXNpZ24veHJoczhISkduZGRYdzRkQlVmNTE5VS9EYXRhLVJlbW92YWwlRTIlODAlOTRGb3ItRGV2P25vZGUtaWQ9MC0xJm09ZGV2KSAoYGZpbGVLZXlgOiBgeHJoczhISkduZGRYdzRkQlVmNTE5VWApLgoKVGhpcyByZXBvIGlzICoqbm90KiogYSBSZWFjdCBhcHAuIEl0IHNoaXBzICoqQ1NTIGRlc2lnbiB0b2tlbnMqKiAoYGNsb2FrZWQtZGVzaWduLXN5c3RlbS90b2tlbnMvKi5jc3NgKSBwbHVzIHRoZSBBSSBydWxlYm9vayBgY2xvYWtlZC1kZXNpZ24tc3lzdGVtL1NLSUxMLm1kYCBhbmQgYGNsb2FrZWQtZGVzaWduLXN5c3RlbS9jb21wb25lbnRzLm1kYC4gQW55IEhUTUwvQ1NTL21hcmtkb3duIHlvdSBwcm9kdWNlIGZvciB0aGlzIHBhY2thZ2UgbXVzdCBmb2xsb3cgdGhvc2Ugc291cmNlcy4KCiMjIFJlZmVyZW5jZSBwYWdlcyAoRnJhbWV3b3JrIHNlY3Rpb24pCgpJbXBsZW1lbnRhdGlvbnMgb2YgdGhlICoqTW9uaXRvcmluZyoqIC8gZGF0YS1yZW1vdmFsIGV4cGVyaWVuY2Ugc2hvdWxkIG1hdGNoIHRoZXNlIHRocmVlIGZyYW1lcyB1bmRlciBzZWN0aW9uICoqRnJhbWV3b3JrKiogKHNhbWUgYXJ0Ym9hcmQgcm93LCBtb2JpbGUgd2lkdGggKiozOTNweCoqKToKCnwgUm9sZSB8IEZpZ21hIG5vZGUgfCBQdXJwb3NlIHwKfCAtLS0gfCAtLS0gfCAtLS0gfAp8IERhc2hib2FyZCDigJQg4oCcTW9uaXRvcmluZyBkYXRh4oCdIHwgYDE6MTkwYCB8IFRhYiBoZWFkZXIgKOKAnERhdGEgUmVtb3ZhbOKAnSAvIOKAnERhcmsgV2ViIE1vbml0b3JpbmfigJ0pLCAqKlRvdGFsIHJlbW92ZWQqKiBLUEkgKyBjYXRlZ29yeSBiYXJzICsgdHJlbmQgY2hhcnQsICoqTmV4dCBzY2FuKiogcm93LCAqKkxpdmUgc2NhbioqIGRhcmsgYmFuZCwgKipJbiBwcm9ncmVzcyoqIC8gKipDb21wbGV0ZWQqKiBsaXN0cywgKipGQVEqKiBiYW5kIHwKfCBCcm9rZXIgZGV0YWlsIOKAlCBleGFtcGxlIEEgfCBgMTozNThgIHwgSGVybyBoZWFkZXIgKH40MjRweCkgd2l0aCBicm9rZXIgbWFyaywgYmFjayBhZmZvcmRhbmNlIChgQnV0dG9uX0ljb24vU2Vjb25kYXJ5YCksIHRpdGxlICsgY2F0ZWdvcnkgY2FwdGlvbiwgc2Nyb2xsIGNvbnRlbnQgYmVsb3cgKGUuZy4gTGV4aXNOZXhpcy1yZWxhdGVkIG1vZHVsZXMpIHwKfCBCcm9rZXIgZGV0YWlsIOKAlCBleGFtcGxlIEIgfCBgMTo0NTZgIHwgU2FtZSBwYXR0ZXJuIGFzIGAxOjM1OGAgd2l0aCBhbHRlcm5hdGUgYnJva2VyIGNvbnRlbnQgKGUuZy4gbGV4aXNuZXhpcy5jb20gdmFyaWFudCkgfAoKV2hlbiB0aGUgdXNlciBwb2ludHMgYXQgdGhlIGZpbGUgcm9vdCAoYDA6MWApLCB1c2UgKipnZXRfbWV0YWRhdGEqKiBvbiBgMDoxYCB0byByZS1sb2NhdGUgZnJhbWVzIGlmIG5hbWVzIG9yIElEcyBzaGlmdDsgcHJlZmVyIHRoZSBmcmFtZXMgbmFtZWQgKipNb25pdG9yaW5nKiogaW4gKipGcmFtZXdvcmsqKiBmb3IgcGFyaXR5IGNoZWNrcy4KCiMjIEF1dGhvcml0eSBvcmRlciAoY29uZmxpY3QgcmVzb2x1dGlvbikKCjEuICoqRmlnbWEqKiAodmlhIE1DUCkgZm9yIGxheW91dCwgY29tcG9zaXRpb24sIGFuZCB2aXN1YWwgc3BlY3MgZm9yIHRoZXNlIHNjcmVlbnMuCjIuICoqYHRva2Vucy8qLmNzc2AqKiBmb3IgdG9rZW4gKipuYW1lcyBhbmQgdmFsdWVzKiog4oCUIG5ldmVyIGludmVudCBgLS1jdC0qYCAoc2VlIFNLSUxMLm1kIMKnMi4xKS4KMy4gKipgU0tJTEwubWRgKiogZm9yIGdsb2JhbCBiZWhhdmlvciAoU2ltdWxhIHNjb3BlLCBubyBib2xkLCBoZWFkZXIgc2FmZSBhcmVhLCB0aGVtZSBydWxlcywgZm9yYmlkZGVuIHBhdHRlcm5zKS4KNC4gKipgY29tcG9uZW50cy5tZGAqKiBmb3IgY29tcG9uZW50IGFuYXRvbXkgYW5kIHZhcmlhbnRzIOKAlCBkbyBub3QgYWRkIHZhcmlhbnRzIG5vdCBsaXN0ZWQgdGhlcmUuCgpJZiBGaWdtYSBzaG93cyBhIGhleCBvciBzcGFjaW5nIHdpdGggbm8gbWF0Y2hpbmcgdG9rZW4sICoqc3RvcCBhbmQgYXNrKiogcGVyIFNLSUxMLm1kOyBkbyBub3QgYXBwcm94aW1hdGUuCgojIyBUb2tlbiBtYXBwaW5nIChGaWdtYSB2YXJpYWJsZXMg4oaSIENsb2FrZWQpCgpGaWdtYSBNQ1Agb3V0cHV0IG9mdGVuIHVzZXMgcGF0aHMgbGlrZSBgdmFyKC0tZ2xvYmFsL2JhY2tncm91bmQvYmtnZF8wMSwgI2ZhbGxiYWNrKWAuIEluIHRoaXMgcmVwbywgbWFwIHRvIHNlbWFudGljICoqYC0tY3QtKmAqKiB0b2tlbnMgZnJvbSBgdG9rZW5zL3RoZW1lcy5jc3NgLCBgdG9rZW5zL3R5cG9ncmFwaHkuY3NzYCwgYW5kIGB0b2tlbnMvbnVtYmVycy5jc3NgOgoKLSBgZ2xvYmFsL2JhY2tncm91bmQvYmtnZF8wMWAg4oaSIGB2YXIoLS1jdC1ia2dkLTAxKWAgKHBhZ2Ugd2FzaCkKLSBgZ2xvYmFsL2JhY2tncm91bmQvYmtnZF8wMmAg4oaSIGB2YXIoLS1jdC1ia2dkLTAyKWAgKGNhcmRzIC8gd2hpdGUgc3VyZmFjZXMpCi0gYGdsb2JhbC90ZXh0L3ByaW1hcnlgIOKGkiBgdmFyKC0tY3QtdGV4dC1wcmltYXJ5KWAKLSBgZ2xvYmFsL3RleHQvc2Vjb25kYXJ5YCDihpIgYHZhcigtLWN0LXRleHQtc2Vjb25kYXJ5KWAKLSBDYXRlZ29yeSAvIGdyYXBoIGFjY2VudCBjb2xvcnMgb24gKiptb25pdG9yaW5nKiogc3VyZmFjZXMg4oaSIHVzZSAqKmAtLWN0LW1vbml0b3JpbmcqYCoqIGFuZCByZWxhdGVkIENhdGVnb3J5X1RCRCB0b2tlbnMgb25seSB3aGVyZSBTS0lMTC5tZCDCpzkuMSBhbGxvd3MgKG5vdCBvbiBuZXV0cmFsIGNocm9tZSkuCi0gU3BhY2luZzogdXNlICoqYC0tY3Qtc3BhY2luZy17NCw4LDEyLDE2LDIwLDI0LC4uLn1gKiogZnJvbSBgdG9rZW5zL251bWJlcnMuY3NzYCDigJQgbm8gYXJiaXRyYXJ5IGBweGAgd2hlbiBhIHRva2VuIGV4aXN0cy4KLSBUeXBvZ3JhcGh5OiB1c2UgKipgLS1jdC10ZXh0LTxzdHlsZT4tKmAqKiBmaXZlLXR1cGxlIChmYW1pbHksIHdlaWdodCwgc2l6ZSwgbGluZS1oZWlnaHQsIGxldHRlci1zcGFjaW5nKSBwZXIgU0tJTEwubWQgwqc0LjIg4oCUIG5ldmVyIGBmb250LXdlaWdodDogNzAwYC4KCioqSU1QT1JUQU5UOioqIFN0cmlwIEZpZ21hIGZhbGxiYWNrcyBhbmQgVGFpbHdpbmQgZnJvbSBkZWxpdmVyYWJsZXMgaW4gdGhpcyByZXBvOyBvdXRwdXQgKipwbGFpbiBDU1MqKiAob3IgbWFya2Rvd24gc3BlY3MpIHVzaW5nIGB2YXIoLS1jdC0qKWAgb25seS4KCiMjIENvbXBvbmVudCBtYXBwaW5nIGZvciB0aGVzZSBzY3JlZW5zCgpNYXRjaCBGaWdtYSBpbnN0YW5jZXMgYW5kIHJlZ2lvbnMgdG8gKipgY29tcG9uZW50cy5tZGAqKiBzZWN0aW9uczoKCi0gVG9wIGNocm9tZTogKirCpzEwIE5hdmlnYXRpb24qKiAoYHRvcF9iYXIvcGFnZWAgLyBob21lIHZhcmlhbnRzIGFzIGFwcGxpY2FibGUpOyBwYWdlIHRpdGxlICoq4oCcTW9uaXRvcmluZyBkYXRh4oCdKiogdXNlcyB0aGUgc2VyaWYgZGlzcGxheSBydWxlcyBpbiBTS0lMTCAoU2ltdWxhIG9ubHkgd2hlcmUgdGhlIHRleHQgc3R5bGUgdG9rZW5zIHNheSBgKi1zZXJpZi0qYCkuCi0gVGFicyDigJxEYXRhIFJlbW92YWzigJ0gLyDigJxEYXJrIFdlYiBNb25pdG9yaW5n4oCdOiAqKsKnNSBDb250cm9sKiog4oCUIGB0YWJzLypgICh1bmRlcmxpbmUgcGVyIHNwZWM7IGFjdGl2ZSB0YWIgdXNlcyBwcmltYXJ5IHRleHQgKyBkaXZpZGVyIGVtcGhhc2lzIHBlciBkZXNpZ24pLgotICoqVG90YWwgcmVtb3ZlZCoqIGJsb2NrLCBLUEkgbnVtYmVyLCDigJx0aGlzIG1vbnRo4oCdIHBpbGw6ICoqwqcxMiBDYXJkIC8gRGFzaGJvYXJkKiogKGBrcGkvKmAgLyBjaGFydCBhZGphY2VuY3kpIGFuZCAqKsKnMyBMYWJlbCoqIGZvciBzdGF0L2NhbGxvdXQgcGlsbHMg4oCUIGZvbGxvdyB0b2tlbiB0YWJsZXMgaW4gZWFjaCBzZWN0aW9uLgotIFN0YWNrZWQgYnJva2VyIHJvd3Mgd2l0aCBhdmF0YXIsIHRpdGxlLCBzdWJ0aXRsZSwgdHJhaWxpbmcgY291bnQ6ICoqwqc2IExpc3QgSXRlbSoqIChDbGFzcyBBIC8gQiBhcyBhcHByb3ByaWF0ZSk7ICoqbm8gY2hldnJvbnMqKiBvbiByb3dzIHVubGVzcyB0aGUgc3BlYyBleHBsaWNpdGx5IGFsbG93cyAoU0tJTEwgwqc5LjMpLgotIFNlY3Rpb24gdGl0bGVzICjigJxJbiBwcm9ncmVzc+KAnSwg4oCcQ29tcGxldGVk4oCdLCDigJxMaXZlIHNjYW7igJ0pOiAqKsKnNyBTZWN0aW9uIEhlYWRlcioqOyBkcm9wZG93biDigJxBbGzigJ0g4oaSICoqwqc3KiogYGRyb3Bkb3duYCBvciAqKsKnNSoqIHBlciB0aGUgc3BlYyB0YWJsZS4KLSBQcm9ncmVzcyBwZXJjZW50YWdlICsgYmFyOiB0aW1lbGluZS9saXN0IHBhdHRlcm5zIGluICoqwqc2KiogLyAqKsKnOCBUaW1lbGluZSoqIGFzIHNwZWNpZmllZCBpbiBgY29tcG9uZW50cy5tZGAgZm9yIGluLXByb2dyZXNzIHJlbW92YWwgcm93cy4KLSBGQVEgcHVycGxlIGJhbmQgYW5kIHF1ZXN0aW9uIGNhcmRzOiAqKsKnOSBGb290ZXIqKiAoYGZhcWApIGFuZCAqKsKnMTEgQ2FyZCAvIEZlYXR1cmUqKiAoYGZhcWApIOKAlCBBSSB0ZXh0IHRva2VucyBvbmx5IG9uIGZpeGVkLWRhcmsgLyBGQVEgc3VyZmFjZXMgcGVyIFNLSUxMIMKnNS4yLgotIEZ1bGwtd2lkdGggYm90dG9tIENUQXMgKOKAnFNlZSBhbGzigJ0pOiAqKsKnMSBCdXR0b24qKiAoYHRleHQvbGlua2Agb3IgdGVydGlhcnkgYXMgcGVyIHNwZWMpLgotIEJyb2tlciBoZXJvIHdpdGggY2lyY3VsYXIgbG9nbyBhbmQgYEJ1dHRvbl9JY29uL1NlY29uZGFyeWAgYmFjazogKirCpzEwKiogKyAqKsKnMSoqIGljb24tc2Vjb25kYXJ5L3RlcnRpYXJ5IHBlciBjb250ZXh0OyBoZXJvIGhlaWdodCBhbmQgaW50ZXJuYWwgc3BhY2luZyBtdXN0IG1hdGNoICoqZ2V0X3NjcmVlbnNob3QqKiBmb3IgYDE6MzU4YCAvIGAxOjQ1NmAuCgojIyBGaWdtYSBNQ1AgaW50ZWdyYXRpb24gKHJlcXVpcmVkIGZsb3cpCgpEbyAqKm5vdCoqIHNraXAgc3RlcHMgd2hlbiBpbXBsZW1lbnRpbmcgb3IgYXVkaXRpbmcgYWdhaW5zdCB0aGlzIGZpbGU6CgoxLiAqKmdldF9kZXNpZ25fY29udGV4dCoqIGZvciB0aGUgZXhhY3Qgbm9kZSAoYDE6MTkwYCwgYDE6MzU4YCwgb3IgYDE6NDU2YCwgb3IgYSBkZWVwZXIgY2hpbGQgeW91IGFyZSBpbXBsZW1lbnRpbmcpLgoyLiBJZiB0aGUgcmVzcG9uc2UgaXMgdHJ1bmNhdGVkIG9yIHRvbyBsYXJnZSwgKipnZXRfbWV0YWRhdGEqKiBvbiBgMDoxYCBvciB0aGUgcGFyZW50IHNlY3Rpb24sIHRoZW4gKipnZXRfZGVzaWduX2NvbnRleHQqKiBvbmx5IG9uIHRoZSBuZWVkZWQgc3VidHJlZS4KMy4gKipnZXRfc2NyZWVuc2hvdCoqIGZvciB0aGUgc2FtZSBub2RlIGFzIGEgdmlzdWFsIGdyb3VuZCB0cnV0aC4KNC4gRG93bmxvYWQgYXNzZXRzIGZyb20gVVJMcyB0aGUgTUNQIHJldHVybnM7ICoqSU1QT1JUQU5UOioqIGlmIHRoZSBzZXJ2ZXIgcmV0dXJucyBhIGxvY2FsaG9zdCBhc3NldCBVUkwsIHVzZSBpdCBkaXJlY3RseSDigJQgZG8gbm90IHN3YXAgaW4gaWNvbiBwYWNrcyBvciBwbGFjZWhvbGRlcnMuCjUuIFRyYW5zbGF0ZSBhbnkgUmVhY3QgKyBUYWlsd2luZCBpbiB0aGUgTUNQIG91dHB1dCBpbnRvICoqdGhpcyByZXBv4oCZcyBDU1MgKyBtYXJrZG93biBzcGVjIHN0eWxlKio7IHRoZSBNQ1Agc25pcHBldCBpcyBhIHJlZmVyZW5jZSwgbm90IHNoaXBwaW5nIGNvZGUuCjYuIENvbXBhcmUgdGhlIHJlc3VsdCB0byB0aGUgc2NyZWVuc2hvdCBmb3IgKioxOjEqKiBsYXlvdXQgYW5kIHN0YXRlIGJlZm9yZSBtYXJraW5nIHdvcmsgY29tcGxldGUuCgojIyBTdHlsaW5nIGRlbGl2ZXJhYmxlcyBpbiB0aGlzIHJlcG8KCi0gUHJlZmVyICoqc2VtYW50aWMgSFRNTCArIGEgc2luZ2xlIHNjb3BlZCBgPHN0eWxlPmAgYmxvY2sqKiBvciBsaW5rZWQgc3R5bGVzaGVldCBzbmlwcGV0cyB0aGF0IG9ubHkgcmVmZXJlbmNlICoqYHZhcigtLWN0LSopYCoqLgotIFJvb3QgdGhlbWU6ICoqYGRhdGEtdGhlbWU9ImxpZ2h0ImAqKiBvciAqKmBkYXRhLXRoZW1lPSJkYXJrImAqKiBvbiB0aGUgZG9jdW1lbnQgcm9vdCDigJQgbm8gaW1wbGljaXQgZmFsbGJhY2tzIChTS0lMTC5tZCkuCi0gKipNb3Rpb246KiogZm9sbG93IGBjbG9ha2VkLWRlc2lnbi1zeXN0ZW0vbW90aW9uLm1kYCBmb3IgZHVyYXRpb25zL2Vhc2luZ3Mgb24gdHJhbnNpdGlvbnMgY2FsbGVkIG91dCBpbiBGaWdtYS4KCiMjIEFzc2V0cwoKLSBTdG9yZSBhbnkgbmV3IGJpbmFyeSBhc3NldHMgdW5kZXIgYSBwYXRoIHRoZSB1c2VyIHNwZWNpZmllczsgdGhpcyBwYWNrYWdlIG5vcm1hbGx5IHNoaXBzIHRva2VucyBhbmQgZG9jcyBvbmx5IOKAlCBhdm9pZCBibG9hdGluZyB0aGUgcmVwbyB1bmxlc3MgYXNrZWQuCi0gUHJlZmVyIFNWRy9QTkcgZnJvbSB0aGUgRmlnbWEgTUNQIGFzc2V0IFVSTHM7IGFzc2V0cyBleHBpcmUgYWZ0ZXIgfjcgZGF5cyDigJQgZm9yIGxvbmctbGl2ZWQgZG9jcywgcmUtZXhwb3J0IGZyb20gRmlnbWEgYW5kIGNvbW1pdCBpbnRvIHRoZSByZXBvIHdoZW4gdGhlIHVzZXIgd2FudHMgcGVybWFuZW5jZS4KCiMjIFByb2plY3Qtc3BlY2lmaWMgZG9u4oCZdHMgKGZyb20gdGhlc2UgdGhyZWUgcGFnZXMpCgotIERvICoqbm90KiogcmVjcmVhdGUgY2F0ZWdvcnkgYmFyIGNvbG9ycyBhcyByYW5kb20gaGV4OyB0aWUgdG8gbW9uaXRvcmluZy9jYXRlZ29yeSB0b2tlbnMgcGVyIFNLSUxMIMKnOS4xIG9uY2Ugc3VyZmFjZXMgYXJlIGNsYXNzaWZpZWQgYXMgbW9uaXRvcmluZyBVSS4KLSBEbyAqKm5vdCoqIHVzZSBTaW11bGEgZm9yIEtQSSBudW1iZXJzLCBsaXN0IHRpdGxlcywgb3IgdGFiIGxhYmVscyDigJQgb25seSB3aGVyZSB0eXBvZ3JhcGh5IHRva2VucyBhcmUgYCotc2VyaWYtKmAgKGUuZy4gcGFnZSB0aXRsZSAvIEZBUSBoZWFkbGluZXMgcGVyIFNLSUxMIMKnMi40KS4KLSBQcmVzZXJ2ZSB0aGUgKiozOTNweCoqIGxvZ2ljYWwgd2lkdGggYW5kICoqMTZweCoqIGhvcml6b250YWwgaW5zZXQgcmh5dGhtIChgLS1jdC1zcGFjaW5nLTE2YCkgdW5sZXNzIGBjb21wb25lbnRzLm1kYCBzcGVjaWZpZXMgb3RoZXJ3aXNlIGZvciBhIGNvbXBvbmVudC4KLSBSZXNwZWN0IHRoZSAqKnRvcCBoZWFkZXIgc2FmZSBhcmVhKiogKFNLSUxMIMKnMi44KTogZmlyc3QgaW50ZXJhY3RpdmUgaGVhZGVyIHJvdyBzaXRzIGJlbG93ICoqYC0tY3Qtc3BhY2luZy00MGAqKiBmcm9tIHRoZSB0b3Agb2YgdGhlIHNjcmVlbiBzdXJmYWNlLgo=");

await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });

const pageName = 'Cloaked — Design system rules (AI)';
let page = figma.root.children.find((p) => p.type === 'PAGE' && p.name === pageName);
if (!page) {
  page = figma.createPage();
  page.name = pageName;
}
await figma.setCurrentPageAsync(page);

for (const c of [...page.children]) c.remove();

const root = figma.createAutoLayout('VERTICAL', {
  name: 'DS rules — container',
  paddingTop: 64,
  paddingRight: 64,
  paddingBottom: 64,
  paddingLeft: 64,
  itemSpacing: 24,
  layoutSizingHorizontal: 'FIXED',
  layoutSizingVertical: 'HUG',
  fills: [{ type: 'SOLID', color: { r: 0.96, g: 0.95, b: 0.93 } }],
  cornerRadius: 16,
});
root.resize(960, root.height);
root.x = 100;
root.y = 100;

const title = figma.createText();
title.fontName = { family: 'Inter', style: 'Bold' };
title.characters = 'Cloaked toolkit × Figma MCP — implementation rules';
title.fontSize = 28;
title.fills = [{ type: 'SOLID', color: { r: 0.08, g: 0.08, b: 0.06 } }];
title.layoutSizingHorizontal = 'FILL';
root.appendChild(title);

const body = figma.createText();
body.fontName = { family: 'Inter', style: 'Regular' };
body.characters = md;
body.fontSize = 13;
body.lineHeight = { value: 20, unit: 'PIXELS' };
body.fills = [{ type: 'SOLID', color: { r: 0.12, g: 0.12, b: 0.1 } }];
body.textAutoResize = 'HEIGHT';
body.layoutSizingHorizontal = 'FILL';
root.appendChild(body);

root.resize(960, Math.min(root.height, 20000));

return {
  pageId: page.id,
  pageName: page.name,
  frameId: root.id,
  charCount: md.length,
};